# Generated by Django 2.1.7 on 2019-03-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_question',
            field=models.TextField(default='This is the main question of the Post'),
        ),
    ]
